taps:
  - koekeishiya/formulae
  - charmbracelet/tap

# Cloud Tools, Applications, and Fonts
cask_packages:
  - docker-desktop
  - google-cloud-sdk
  - applite
  - font-caskaydia-mono-nerd-font
  - font-droid-sans-mono-nerd-font
  - font-inconsolata-nerd-font
  - font-fira-code-nerd-font
  - font-jetbrains-mono-nerd-font
  - google-chrome
  - ghostty
  - git-credential-manager
  - iterm2
  - maccy
  - cameracontroller
  - visual-studio-code
  - slack
  - zoom
  - monitorcontrol
  - copilot-cli

homebrew_packages:
  # Cloud Tools
  - awscli
  - chafa
  - eza
  - docker-credential-helper-ecr
  - kubernetes-cli
  - k9s
  - kind
  - kubectx
  - skaffold
  - stern
  - lima
  - atuin
  - bat
  - bc
  - charmbracelet/tap/gum
  - btop
  - fastfetch
  - fd
  - gnupg
  - jless
  - just
  - pinentry-mac
  - mactop
  - mergiraf
  - mkcert
  - nss
  - ripgrep
  - thefuck
  - fzf
  - navi
  - jq
  - yadm
  - tmate
  - tmux
  - watch
  - zoxide
  - starship
  - openssl@3
  - koekeishiya/formulae/skhd
  - imagemagick
  - mas
  - gh
  - glab
  - "node"
  - "php@8.2"
  - golang
  - gitleaks
  - uv
  - llm
  - yarn
  - yarn-completion

linked_packages: []

# Removed packages/taps
removed_homebrew_packages:
  - "node@20"
  - docker-compose
  - neofetch
  - "php@8.3"

removed_taps:
  - homebrew/cask-versions
  - homebrew/cask-fonts
  - homebrew/homebrew-cask-fonts
  - homebrew/cask-drivers

removed_cask_packages: []
